# Obsolete for now, GKE issues.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nimonspedia-ingress
spec:
  ingressClassName: gce
  rules:
  - host: nimonspedia.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nimonspedia-node-service
            port:
              number: 80
