apiVersion: v1
kind: Service
metadata:
  name: nimonspedia-node-service
spec:
  type: NodePort
  selector:
    app: nimonspedia-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
