apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimonspedia-node
  labels:
    app: nimonspedia-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nimonspedia-node
  template:
    metadata:
      labels:
        app: nimonspedia-node
    spec:
      serviceAccountName: nimonspedia-ksa
      containers:
        - name: nimonspedia-node
          image: ghcr.io/mraifalkautsar/node-app/nimonspedia-node:68784c2ec6b7187e6f91bcb8292ccde421a1d121
          ports:
            - containerPort: 3000

          env:
            # Sourced from the configmap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nimonspedia-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nimonspedia-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nimonspedia-config
                  key: DB_NAME

          volumeMounts:
            # GCP Secret Manager via CSI (read-only)
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

            # Uploads (for app uploads)
            - name: uploads
              mountPath: "/uploads"

          resources:
            requests:
              cpu: "40m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

      volumes:
        # CSI secrets
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "nimonspedia-gcp-secrets"

        # Writable volume for uploads
        - name: uploads
          emptyDir: {}
